import type { Grammar, Vocabulary } from "./types";

export const chapter61Vocabulary: Vocabulary[] = [
  { id: "vocab-6-1-1", korean: "십 원", meaning: "10韓元 / 10 won", part_of_speech: "N", origin: "漢字詞", example_sentence: "", related_words: "오십 원, 백 원", chapters: ["6-1"], source: "課本", quiz_count: 0, correct_streak: 0, familiarity: "no" },
  { id: "vocab-6-1-2", korean: "오십 원", meaning: "50韓元 / 50 won", part_of_speech: "N", origin: "漢字詞", example_sentence: "", related_words: "십 원, 백 원", chapters: ["6-1"], source: "課本", quiz_count: 0, correct_streak: 0, familiarity: "no" },
  { id: "vocab-6-1-3", korean: "백 원", meaning: "100韓元 / 100 won", part_of_speech: "N", origin: "漢字詞", example_sentence: "", related_words: "오백 원, 천 원", chapters: ["6-1"], source: "課本", quiz_count: 0, correct_streak: 0, familiarity: "no" },
  { id: "vocab-6-1-4", korean: "오백 원", meaning: "500韓元 / 500 won", part_of_speech: "N", origin: "漢字詞", example_sentence: "", related_words: "백 원, 천 원", chapters: ["6-1"], source: "課本", quiz_count: 0, correct_streak: 0, familiarity: "no" },
  { id: "vocab-6-1-5", korean: "천 원", meaning: "1,000韓元 / 1,000 won", part_of_speech: "N", origin: "漢字詞", example_sentence: "", related_words: "오천 원, 만 원", chapters: ["6-1"], source: "課本", quiz_count: 0, correct_streak: 0, familiarity: "no" },
  { id: "vocab-6-1-6", korean: "오천 원", meaning: "5,000韓元 / 5,000 won", part_of_speech: "N", origin: "漢字詞", example_sentence: "", related_words: "천 원, 만 원", chapters: ["6-1"], source: "課本", quiz_count: 0, correct_streak: 0, familiarity: "no" },
  { id: "vocab-6-1-7", korean: "만 원", meaning: "10,000韓元 / 10,000 won", part_of_speech: "N", origin: "漢字詞", example_sentence: "", related_words: "오만 원, 십만 원", chapters: ["6-1"], source: "課本", quiz_count: 0, correct_streak: 0, familiarity: "no" },
  { id: "vocab-6-1-8", korean: "오만 원", meaning: "50,000韓元 / 50,000 won", part_of_speech: "N", origin: "漢字詞", example_sentence: "", related_words: "만 원, 십만 원", chapters: ["6-1"], source: "課本", quiz_count: 0, correct_streak: 0, familiarity: "no" },
  { id: "vocab-6-1-9", korean: "십만 원", meaning: "100,000韓元 / 100,000 won", part_of_speech: "N", origin: "漢字詞", example_sentence: "", related_words: "오만 원, 백만 원", chapters: ["6-1"], source: "課本", quiz_count: 0, correct_streak: 0, familiarity: "no" },
  { id: "vocab-6-1-10", korean: "백만 원", meaning: "1,000,000韓元 / 1,000,000 won", part_of_speech: "N", origin: "漢字詞", example_sentence: "", related_words: "십만 원, 천만 원", chapters: ["6-1"], source: "課本", quiz_count: 0, correct_streak: 0, familiarity: "no" },
  { id: "vocab-6-1-11", korean: "천만 원", meaning: "10,000,000韓元 / 10,000,000 won", part_of_speech: "N", origin: "漢字詞", example_sentence: "", related_words: "백만 원", chapters: ["6-1"], source: "課本", quiz_count: 0, correct_streak: 0, familiarity: "no" },
  { id: "vocab-6-1-12", korean: "개", meaning: "個、一般物品量詞 / thing, general counter", part_of_speech: "N", origin: "固有語", example_sentence: "", related_words: "병, 캔", chapters: ["6-1"], source: "課本", quiz_count: 0, correct_streak: 0, familiarity: "no" },
  { id: "vocab-6-1-13", korean: "권", meaning: "冊、本的量詞 / volume", part_of_speech: "N", origin: "漢字詞", example_sentence: "", related_words: "", chapters: ["6-1"], source: "課本", quiz_count: 0, correct_streak: 0, familiarity: "no" },
  { id: "vocab-6-1-14", korean: "명", meaning: "名、人的量詞 / person", part_of_speech: "N", origin: "漢字詞", example_sentence: "", related_words: "사람", chapters: ["6-1"], source: "課本", quiz_count: 0, correct_streak: 0, familiarity: "no" },
  { id: "vocab-6-1-15", korean: "병", meaning: "瓶 / bottle", part_of_speech: "N", origin: "漢字詞", example_sentence: "", related_words: "캔", chapters: ["6-1"], source: "課本", quiz_count: 0, correct_streak: 0, familiarity: "no" },
  { id: "vocab-6-1-16", korean: "캔", meaning: "罐 / can", part_of_speech: "N", origin: "外來語", example_sentence: "", related_words: "병", chapters: ["6-1"], source: "課本", quiz_count: 0, correct_streak: 0, familiarity: "no" },
  { id: "vocab-6-1-17", korean: "켤레", meaning: "雙、對 / pair", part_of_speech: "N", origin: "固有語", example_sentence: "", related_words: "신발, 양말", chapters: ["6-1"], source: "課本", quiz_count: 0, correct_streak: 0, familiarity: "no" },
  { id: "vocab-6-1-18", korean: "가격", meaning: "價格 / price", part_of_speech: "N", origin: "漢字詞", example_sentence: "", related_words: "얼마", chapters: ["6-1"], source: "課本", quiz_count: 0, correct_streak: 0, familiarity: "no" },
  { id: "vocab-6-1-19", korean: "감사합니다", meaning: "謝謝 / Thank you", part_of_speech: "V", origin: "漢字詞", example_sentence: "", related_words: "", chapters: ["6-1"], source: "課本", quiz_count: 0, correct_streak: 0, familiarity: "no" },
  { id: "vocab-6-1-20", korean: "계시다", meaning: "在、有、存在（敬語） / to exist, polite", part_of_speech: "V", origin: "固有語", example_sentence: "", related_words: "있다", chapters: ["6-1"], source: "課本", quiz_count: 0, correct_streak: 0, familiarity: "no" },
  { id: "vocab-6-1-21", korean: "과자", meaning: "點心、零食 / snacks", part_of_speech: "N", origin: "漢字詞", example_sentence: "", related_words: "", chapters: ["6-1"], source: "課本", quiz_count: 0, correct_streak: 0, familiarity: "no" },
  { id: "vocab-6-1-22", korean: "그럼", meaning: "那麼、那樣的話 / then, in that case", part_of_speech: "Adv", origin: "固有語", example_sentence: "", related_words: "", chapters: ["6-1"], source: "課本", quiz_count: 0, correct_streak: 0, familiarity: "no" },
  { id: "vocab-6-1-23", korean: "담배", meaning: "香菸 / cigarette", part_of_speech: "N", origin: "外來語", example_sentence: "", related_words: "피우다", chapters: ["6-1"], source: "課本", quiz_count: 0, correct_streak: 0, familiarity: "no" },
  { id: "vocab-6-1-24", korean: "드시다", meaning: "吃、喝（敬語） / to eat, polite", part_of_speech: "V", origin: "固有語", example_sentence: "", related_words: "먹다", chapters: ["6-1"], source: "課本", quiz_count: 0, correct_streak: 0, familiarity: "no" },
  { id: "vocab-6-1-25", korean: "또", meaning: "又、再 / again", part_of_speech: "Adv", origin: "固有語", example_sentence: "", related_words: "", chapters: ["6-1"], source: "課本", quiz_count: 0, correct_streak: 0, familiarity: "no" },
  { id: "vocab-6-1-26", korean: "붕어빵", meaning: "鯽魚餅 / bungeobbang, fish-shaped pastry", part_of_speech: "N", origin: "固有語", example_sentence: "", related_words: "", chapters: ["6-1"], source: "課本", quiz_count: 0, correct_streak: 0, familiarity: "no" },
  { id: "vocab-6-1-27", korean: "삼각김밥", meaning: "三角飯糰 / triangle gimbap", part_of_speech: "N", origin: "漢字詞", example_sentence: "", related_words: "김밥", chapters: ["6-1"], source: "課本", quiz_count: 0, correct_streak: 0, familiarity: "no" },
  { id: "vocab-6-1-28", korean: "샤프", meaning: "自動鉛筆 / mechanical pencil", part_of_speech: "N", origin: "外來語", example_sentence: "", related_words: "", chapters: ["6-1"], source: "課本", quiz_count: 0, correct_streak: 0, familiarity: "no" },
  { id: "vocab-6-1-29", korean: "샴푸", meaning: "洗髮精 / shampoo", part_of_speech: "N", origin: "外來語", example_sentence: "", related_words: "", chapters: ["6-1"], source: "課本", quiz_count: 0, correct_streak: 0, familiarity: "no" },
  { id: "vocab-6-1-30", korean: "신발", meaning: "鞋子 / shoes", part_of_speech: "N", origin: "固有語", example_sentence: "", related_words: "양말, 켤레", chapters: ["6-1"], source: "課本", quiz_count: 0, correct_streak: 0, familiarity: "no" },
  { id: "vocab-6-1-31", korean: "안녕히 가세요", meaning: "再見（請走好） / Goodbye, Go well", part_of_speech: "V", origin: "漢字詞", example_sentence: "", related_words: "안녕히 계세요", chapters: ["6-1"], source: "課本", quiz_count: 0, correct_streak: 0, familiarity: "no" },
  { id: "vocab-6-1-32", korean: "안녕히 계세요", meaning: "再見（請留好） / Goodbye, Stay well", part_of_speech: "V", origin: "漢字詞", example_sentence: "", related_words: "안녕히 가세요", chapters: ["6-1"], source: "課本", quiz_count: 0, correct_streak: 0, familiarity: "no" },
  { id: "vocab-6-1-33", korean: "양말", meaning: "襪子 / socks", part_of_speech: "N", origin: "漢字詞", example_sentence: "", related_words: "신발, 켤레", chapters: ["6-1"], source: "課本", quiz_count: 0, correct_streak: 0, familiarity: "no" },
  { id: "vocab-6-1-34", korean: "어서 오세요", meaning: "歡迎光臨 / Welcome", part_of_speech: "V", origin: "固有語", example_sentence: "", related_words: "", chapters: ["6-1"], source: "課本", quiz_count: 0, correct_streak: 0, familiarity: "no" },
  { id: "vocab-6-1-35", korean: "얼마", meaning: "多少 / how much", part_of_speech: "N", origin: "固有語", example_sentence: "", related_words: "가격", chapters: ["6-1"], source: "課本", quiz_count: 0, correct_streak: 0, familiarity: "no" },
  { id: "vocab-6-1-36", korean: "에어컨", meaning: "冷氣、空調 / air conditioner", part_of_speech: "N", origin: "外來語", example_sentence: "", related_words: "", chapters: ["6-1"], source: "課本", quiz_count: 0, correct_streak: 0, familiarity: "no" },
  { id: "vocab-6-1-37", korean: "여기요", meaning: "這裡、給你 / Here, Here you are", part_of_speech: "Adv", origin: "固有語", example_sentence: "", related_words: "여기", chapters: ["6-1"], source: "課本", quiz_count: 0, correct_streak: 0, familiarity: "no" },
  { id: "vocab-6-1-38", korean: "이야기를 하다", meaning: "說話、聊天 / to speak, to talk", part_of_speech: "V", origin: "固有語", example_sentence: "", related_words: "말하다", chapters: ["6-1"], source: "課本", quiz_count: 0, correct_streak: 0, familiarity: "no" },
  { id: "vocab-6-1-39", korean: "인기", meaning: "人氣 / popularity", part_of_speech: "N", origin: "漢字詞", example_sentence: "", related_words: "", chapters: ["6-1"], source: "課本", quiz_count: 0, correct_streak: 0, familiarity: "no" },
  { id: "vocab-6-1-40", korean: "주무시다", meaning: "睡覺（敬語） / to sleep, polite", part_of_speech: "V", origin: "固有語", example_sentence: "", related_words: "자다", chapters: ["6-1"], source: "課本", quiz_count: 0, correct_streak: 0, familiarity: "no" },
  { id: "vocab-6-1-41", korean: "죄송합니다", meaning: "對不起 / Sorry, polite speech", part_of_speech: "V", origin: "漢字詞", example_sentence: "", related_words: "미안합니다", chapters: ["6-1"], source: "課本", quiz_count: 0, correct_streak: 0, familiarity: "no" },
  { id: "vocab-6-1-42", korean: "직원", meaning: "職員、店員 / staff, employee", part_of_speech: "N", origin: "漢字詞", example_sentence: "", related_words: "", chapters: ["6-1"], source: "課本", quiz_count: 0, correct_streak: 0, familiarity: "no" },
  { id: "vocab-6-1-43", korean: "천천히", meaning: "慢慢地 / slowly", part_of_speech: "Adv", origin: "固有語", example_sentence: "", related_words: "", chapters: ["6-1"], source: "課本", quiz_count: 0, correct_streak: 0, familiarity: "no" },
  { id: "vocab-6-1-44", korean: "콜라", meaning: "可樂 / cola, soda", part_of_speech: "N", origin: "外來語", example_sentence: "", related_words: "", chapters: ["6-1"], source: "課本", quiz_count: 0, correct_streak: 0, familiarity: "no" },
  { id: "vocab-6-1-45", korean: "팔다", meaning: "賣 / to sell", part_of_speech: "V", origin: "固有語", example_sentence: "", related_words: "사다", chapters: ["6-1"], source: "課本", quiz_count: 0, correct_streak: 0, familiarity: "no" },
  { id: "vocab-6-1-46", korean: "피우다", meaning: "抽、抽菸 / to smoke", part_of_speech: "V", origin: "固有語", example_sentence: "", related_words: "담배", chapters: ["6-1"], source: "課本", quiz_count: 0, correct_streak: 0, familiarity: "no" },
  { id: "vocab-6-1-47", korean: "할인을 하다", meaning: "打折 / to give a discount", part_of_speech: "V", origin: "漢字詞", example_sentence: "", related_words: "가격", chapters: ["6-1"], source: "課本", quiz_count: 0, correct_streak: 0, familiarity: "no" }
];

export const chapter61Grammar: Grammar[] = [
  {
    id: "grammar-6-1-1",
    pattern: "N이/가 얼마예요?",
    meaning_zh: "用來詢問價格：N多少錢？\n詢問某物多少錢。",
    meaning_en: "An expression used when asking a price.\nUsed to ask how much something costs.",
    example_sentence: "이 우산은 12,000원이에요. / 이 빵이 얼마예요?",
    cloze_question: "이 우산은 ______원이에요.",
    cloze_answer: "12,000",
    translation_question: "請翻譯：這把雨傘是12,000韓元。",
    translation_reference_answer: "이 우산은 12,000원이에요.",
    extra_vocab_explanation: "우산：雨傘 / umbrella；빵：麵包 / bread",
    chapters: ["6-1"],
    source: "課本",
    quiz_count: 0,
    correct_streak: 0,
    familiarity: "no"
  },
  {
    id: "grammar-6-1-2",
    pattern: "N은/는 Num개에 Num원이에요",
    meaning_zh: "用來回答價格：N是幾個多少韓元。",
    meaning_en: "Used to answer a price: N is __ won for __.",
    example_sentence: "사과는 3개에 3,000원이에요.",
    cloze_question: "사과는 3개에 ______원이에요.",
    cloze_answer: "3,000",
    translation_question: "請翻譯：蘋果3個3,000韓元。",
    translation_reference_answer: "사과는 3개에 3,000원이에요.",
    extra_vocab_explanation: "사과：蘋果 / apple",
    chapters: ["6-1"],
    source: "課本",
    quiz_count: 0,
    correct_streak: 0,
    familiarity: "no"
  },
  {
    id: "grammar-6-1-3",
    pattern: "V-(으)세요",
    meaning_zh: "接在動詞語幹後，用來命令或請求對方做某動作。意思是「請……」。\n接在動詞語幹後，用來命令或請求對方做某動作。먹다、마시다、잠을 자다、있다 等有特殊敬語形式。",
    meaning_en: "Attaches to a verb stem and is used when ordering or requesting that another person does an action.\nUsed for requests or commands. Some verbs such as 먹다, 마시다, 잠을 자다, and 있다 use special polite forms.",
    example_sentence: "한국어로 이야기하세요. / 손을 자주 씻으세요. / 이 약을 드세요. 그리고 일찍 주무세요.",
    cloze_question: "한국어로 ______.",
    cloze_answer: "이야기하세요",
    translation_question: "請翻譯：請用韓文說。",
    translation_reference_answer: "한국어로 이야기하세요.",
    extra_vocab_explanation: "이야기를 하다：說話、聊天 / to speak, to talk；손：手 / hand, 자주：常常 / often；드시다：吃、喝的敬語；주무시다：睡覺的敬語",
    chapters: ["6-1"],
    source: "課本",
    quiz_count: 0,
    correct_streak: 0,
    familiarity: "no"
  },
  {
    id: "grammar-6-1-4",
    pattern: "V-지 마세요",
    meaning_zh: "接在動詞語幹後，用來阻止聽者做某個動作。意思是「請不要……」。",
    meaning_en: "Attaches to a verb stem to indicate preventing the listener from doing a certain action.",
    example_sentence: "여기에서 사진을 찍지 마세요. / 화장실에서 담배를 피우지 마세요.",
    cloze_question: "여기에서 사진을 ______.",
    cloze_answer: "찍지 마세요",
    translation_question: "請翻譯：請不要在這裡拍照。",
    translation_reference_answer: "여기에서 사진을 찍지 마세요.",
    extra_vocab_explanation: "사진을 찍다：拍照 / to take a picture；담배：香菸 / cigarette, 피우다：抽、抽菸 / to smoke",
    chapters: ["6-1"],
    source: "課本",
    quiz_count: 0,
    correct_streak: 0,
    familiarity: "no"
  }
];
