import type { Grammar, Vocabulary } from "./types";

export const chapter52Vocabulary: Vocabulary[] = [
  {
    id: "vocab-5-2-1",
    korean: "게임을 하다",
    meaning: "玩遊戲 / to play games",
    part_of_speech: "V",
    origin: "",
    example_sentence: "",
    related_words: "",
    chapters: ["5-2"],
    source: "課本",
    quiz_count: 0,
    correct_streak: 0,
    familiarity: "no"
  },
  {
    id: "vocab-5-2-2",
    korean: "낮잠을 자다",
    meaning: "睡午覺 / to take a nap",
    part_of_speech: "V",
    origin: "",
    example_sentence: "",
    related_words: "",
    chapters: ["5-2"],
    source: "課本",
    quiz_count: 0,
    correct_streak: 0,
    familiarity: "no"
  },
  {
    id: "vocab-5-2-3",
    korean: "단어를 외우다",
    meaning: "背單字 / to memorize vocabulary",
    part_of_speech: "V",
    origin: "",
    example_sentence: "",
    related_words: "",
    chapters: ["5-2"],
    source: "課本",
    quiz_count: 0,
    correct_streak: 0,
    familiarity: "no"
  },
  {
    id: "vocab-5-2-4",
    korean: "머리를 하다",
    meaning: "做頭髮 / to do one's hair",
    part_of_speech: "V",
    origin: "",
    example_sentence: "",
    related_words: "",
    chapters: ["5-2"],
    source: "課本",
    quiz_count: 0,
    correct_streak: 0,
    familiarity: "no"
  },
  {
    id: "vocab-5-2-5",
    korean: "아르바이트를 하다",
    meaning: "打工 / to work a part-time job",
    part_of_speech: "V",
    origin: "外來語",
    example_sentence: "",
    related_words: "",
    chapters: ["5-2"],
    source: "課本",
    quiz_count: 0,
    correct_streak: 0,
    familiarity: "no"
  },
  {
    id: "vocab-5-2-6",
    korean: "운동을 하다",
    meaning: "運動 / to work out",
    part_of_speech: "V",
    origin: "漢字詞",
    example_sentence: "",
    related_words: "",
    chapters: ["5-2"],
    source: "課本",
    quiz_count: 0,
    correct_streak: 0,
    familiarity: "no"
  },
  {
    id: "vocab-5-2-7",
    korean: "장을 보다",
    meaning: "買菜；採買 / to go grocery shopping",
    part_of_speech: "V",
    origin: "",
    example_sentence: "",
    related_words: "",
    chapters: ["5-2"],
    source: "課本",
    quiz_count: 0,
    correct_streak: 0,
    familiarity: "no"
  },
  {
    id: "vocab-5-2-8",
    korean: "청소를 하다",
    meaning: "打掃 / to clean",
    part_of_speech: "V",
    origin: "漢字詞",
    example_sentence: "",
    related_words: "",
    chapters: ["5-2"],
    source: "課本",
    quiz_count: 0,
    correct_streak: 0,
    familiarity: "no"
  },
  {
    id: "vocab-5-2-9",
    korean: "텔레비전을 보다",
    meaning: "看電視 / to watch TV",
    part_of_speech: "V",
    origin: "外來語",
    example_sentence: "",
    related_words: "",
    chapters: ["5-2"],
    source: "課本",
    quiz_count: 0,
    correct_streak: 0,
    familiarity: "no"
  },
  {
    id: "vocab-5-2-10",
    korean: "듣다",
    meaning: "聽 / to listen, to hear",
    part_of_speech: "V",
    origin: "固有語",
    example_sentence: "",
    related_words: "",
    chapters: ["5-2"],
    source: "課本",
    quiz_count: 0,
    correct_streak: 0,
    familiarity: "no"
  },
  {
    id: "vocab-5-2-11",
    korean: "묻다",
    meaning: "問 / to ask",
    part_of_speech: "V",
    origin: "固有語",
    example_sentence: "",
    related_words: "",
    chapters: ["5-2"],
    source: "課本",
    quiz_count: 0,
    correct_streak: 0,
    familiarity: "no"
  },
  {
    id: "vocab-5-2-12",
    korean: "걷다",
    meaning: "走路 / to walk",
    part_of_speech: "V",
    origin: "固有語",
    example_sentence: "",
    related_words: "",
    chapters: ["5-2"],
    source: "課本",
    quiz_count: 0,
    correct_streak: 0,
    familiarity: "no"
  },
  {
    id: "vocab-5-2-13",
    korean: "그래요?",
    meaning: "真的嗎？ / Really?",
    part_of_speech: "",
    origin: "",
    example_sentence: "",
    related_words: "",
    chapters: ["5-2"],
    source: "課本",
    quiz_count: 0,
    correct_streak: 0,
    familiarity: "no"
  },
  {
    id: "vocab-5-2-14",
    korean: "드라마",
    meaning: "電視劇 / TV drama",
    part_of_speech: "N",
    origin: "外來語",
    example_sentence: "",
    related_words: "",
    chapters: ["5-2"],
    source: "課本",
    quiz_count: 0,
    correct_streak: 0,
    familiarity: "no"
  },
  {
    id: "vocab-5-2-15",
    korean: "마트",
    meaning: "超市 / mart",
    part_of_speech: "N",
    origin: "外來語",
    example_sentence: "",
    related_words: "",
    chapters: ["5-2"],
    source: "課本",
    quiz_count: 0,
    correct_streak: 0,
    familiarity: "no"
  },
  {
    id: "vocab-5-2-16",
    korean: "미용실",
    meaning: "美容院；髮廊 / hair salon",
    part_of_speech: "N",
    origin: "漢字詞",
    example_sentence: "",
    related_words: "",
    chapters: ["5-2"],
    source: "課本",
    quiz_count: 0,
    correct_streak: 0,
    familiarity: "no"
  },
  {
    id: "vocab-5-2-17",
    korean: "받다",
    meaning: "收；得到 / to receive, to get",
    part_of_speech: "V",
    origin: "固有語",
    example_sentence: "",
    related_words: "",
    chapters: ["5-2"],
    source: "課本",
    quiz_count: 0,
    correct_streak: 0,
    familiarity: "no"
  },
  {
    id: "vocab-5-2-18",
    korean: "손님",
    meaning: "客人 / customer, guest",
    part_of_speech: "N",
    origin: "",
    example_sentence: "",
    related_words: "",
    chapters: ["5-2"],
    source: "課本",
    quiz_count: 0,
    correct_streak: 0,
    familiarity: "no"
  },
  {
    id: "vocab-5-2-19",
    korean: "수업을 듣다",
    meaning: "上課；聽課 / to take a class",
    part_of_speech: "V",
    origin: "漢字詞",
    example_sentence: "",
    related_words: "",
    chapters: ["5-2"],
    source: "課本",
    quiz_count: 0,
    correct_streak: 0,
    familiarity: "no"
  },
  {
    id: "vocab-5-2-20",
    korean: "요즘",
    meaning: "最近；這些日子 / recently, these days",
    part_of_speech: "Adv",
    origin: "",
    example_sentence: "",
    related_words: "",
    chapters: ["5-2"],
    source: "課本",
    quiz_count: 0,
    correct_streak: 0,
    familiarity: "no"
  },
  {
    id: "vocab-5-2-21",
    korean: "음악",
    meaning: "音樂 / music",
    part_of_speech: "N",
    origin: "漢字詞",
    example_sentence: "",
    related_words: "",
    chapters: ["5-2"],
    source: "課本",
    quiz_count: 0,
    correct_streak: 0,
    familiarity: "no"
  },
  {
    id: "vocab-5-2-22",
    korean: "이날",
    meaning: "這一天 / this day",
    part_of_speech: "N",
    origin: "",
    example_sentence: "",
    related_words: "",
    chapters: ["5-2"],
    source: "課本",
    quiz_count: 0,
    correct_streak: 0,
    familiarity: "no"
  },
  {
    id: "vocab-5-2-23",
    korean: "인터넷을 하다",
    meaning: "上網 / to use the internet",
    part_of_speech: "V",
    origin: "外來語",
    example_sentence: "",
    related_words: "",
    chapters: ["5-2"],
    source: "課本",
    quiz_count: 0,
    correct_streak: 0,
    familiarity: "no"
  },
  {
    id: "vocab-5-2-24",
    korean: "일찍",
    meaning: "早早地 / early",
    part_of_speech: "Adv",
    origin: "",
    example_sentence: "",
    related_words: "",
    chapters: ["5-2"],
    source: "課本",
    quiz_count: 0,
    correct_streak: 0,
    familiarity: "no"
  },
  {
    id: "vocab-5-2-25",
    korean: "힘들다",
    meaning: "辛苦；困難 / to be hard",
    part_of_speech: "A",
    origin: "",
    example_sentence: "",
    related_words: "",
    chapters: ["5-2"],
    source: "課本",
    quiz_count: 0,
    correct_streak: 0,
    familiarity: "no"
  }
];

export const chapter52Grammar: Grammar[] = [
  {
    id: "grammar-5-2-1",
    pattern: "V-(으)ㄹ 거예요",
    meaning_zh: "表示未來會發生的事件、計畫或預測。有收音用 -을 거예요，沒有收音用 -ㄹ 거예요。",
    meaning_en: "Attaches to a verb stem to indicate events, plans, and predictions that will occur in the future.",
    example_sentence: "저는 오후에 책을 읽을 거예요. / 저는 오늘 일찍 잘 거예요.",
    cloze_question: "저는 오늘 일찍 잘 ____.",
    cloze_answer: "거예요",
    translation_question: "請翻譯：이번 주말에 뭐 할 거예요?",
    translation_reference_answer: "這個週末你要做什麼？",
    extra_vocab_explanation: "오후: 下午；오늘: 今天；일찍: 早早地；주말: 週末；청소하다: 打掃",
    chapters: ["5-2"],
    source: "課本",
    quiz_count: 0,
    correct_streak: 0,
    familiarity: "no"
  },
  {
    id: "grammar-5-2-2",
    pattern: "V-ㄷ 불규칙",
    meaning_zh: "ㄷ 不規則：部分以收音 ㄷ 結尾的動詞，接以母音開始的語尾時，ㄷ 變成 ㄹ。例：듣다 + 어요 → 들어요。",
    meaning_en: "When combined with a verb ending that begins with a vowel, some verbs ending with final consonant ㄷ change ㄷ to ㄹ.",
    example_sentence: "마크는 수업을 들어요. / 저는 매일 공원에서 걸어요.",
    cloze_question: "마크는 수업을 ____.",
    cloze_answer: "들어요",
    translation_question: "請翻譯：저는 매일 공원에서 걸어요.",
    translation_reference_answer: "我每天在公園走路。",
    extra_vocab_explanation: "듣다: 聽；걷다: 走路；묻다: 問。닫다、받다 不屬於此不規則變化。",
    chapters: ["5-2"],
    source: "課本",
    quiz_count: 0,
    correct_streak: 0,
    familiarity: "no"
  }
];
