import type { Grammar, QuizAnswer, QuizSession, UserSettings, Vocabulary } from "./types";
import { chapter52Grammar, chapter52Vocabulary } from "./chapter-5-2-data";
import { chapter61Grammar, chapter61Vocabulary } from "./chapter-6-1-data";

export const mockVocabulary: Vocabulary[] = [
  {
    id: "vocab-1",
    korean: "날짜",
    meaning: "日期 / date",
    part_of_speech: "名詞",
    origin: "漢字詞",
    example_sentence: "오늘 날짜가 어떻게 돼요?",
    related_words: "오늘, 내일",
    chapters: ["1-1"],
    source: "課本",
    quiz_count: 2,
    correct_streak: 2,
    familiarity: "no"
  },
  {
    id: "vocab-2",
    korean: "공부하다",
    meaning: "讀書 / study",
    part_of_speech: "動詞",
    origin: "漢字詞",
    example_sentence: "저는 학교에서 공부해요.",
    related_words: "학교",
    chapters: ["1-1", "2-1"],
    source: "自行補充",
    quiz_count: 3,
    correct_streak: 3,
    familiarity: "yes"
  },
  {
    id: "vocab-3",
    korean: "눈",
    meaning: "雪 / snow；眼睛 / eye",
    part_of_speech: "名詞",
    origin: "固有語",
    example_sentence: "눈이 와요.",
    related_words: "겨울",
    chapters: ["2-1"],
    source: "AI詢問",
    quiz_count: 1,
    correct_streak: 0,
    familiarity: "no"
  },
  {
    id: "vocab-5-3-1",
    korean: "오전",
    meaning: "上午 / morning, a.m.",
    part_of_speech: "N",
    origin: "漢字詞",
    example_sentence: "",
    related_words: "오후",
    chapters: ["5-3"],
    source: "課本",
    quiz_count: 0,
    correct_streak: 0,
    familiarity: "no"
  },
  {
    id: "vocab-5-3-2",
    korean: "오후",
    meaning: "下午 / afternoon, p.m.",
    part_of_speech: "N",
    origin: "漢字詞",
    example_sentence: "",
    related_words: "오전",
    chapters: ["5-3"],
    source: "課本",
    quiz_count: 0,
    correct_streak: 0,
    familiarity: "no"
  },
  {
    id: "vocab-5-3-3",
    korean: "새벽",
    meaning: "凌晨 / dawn, middle of the night",
    part_of_speech: "N",
    origin: "固有語",
    example_sentence: "",
    related_words: "",
    chapters: ["5-3"],
    source: "課本",
    quiz_count: 0,
    correct_streak: 0,
    familiarity: "no"
  },
  {
    id: "vocab-5-3-4",
    korean: "아침",
    meaning: "早上 / morning",
    part_of_speech: "N",
    origin: "固有語",
    example_sentence: "",
    related_words: "",
    chapters: ["5-3"],
    source: "課本",
    quiz_count: 0,
    correct_streak: 0,
    familiarity: "no"
  },
  {
    id: "vocab-5-3-5",
    korean: "낮",
    meaning: "白天 / daytime",
    part_of_speech: "N",
    origin: "固有語",
    example_sentence: "",
    related_words: "밤",
    chapters: ["5-3"],
    source: "課本",
    quiz_count: 0,
    correct_streak: 0,
    familiarity: "no"
  },
  {
    id: "vocab-5-3-6",
    korean: "저녁",
    meaning: "傍晚、晚上 / evening",
    part_of_speech: "N",
    origin: "固有語",
    example_sentence: "",
    related_words: "",
    chapters: ["5-3"],
    source: "課本",
    quiz_count: 0,
    correct_streak: 0,
    familiarity: "no"
  },
  {
    id: "vocab-5-3-7",
    korean: "밤",
    meaning: "夜晚、晚上 / night",
    part_of_speech: "N",
    origin: "固有語",
    example_sentence: "",
    related_words: "낮",
    chapters: ["5-2", "5-3"],
    source: "課本",
    quiz_count: 0,
    correct_streak: 0,
    familiarity: "no"
  },
  {
    id: "vocab-5-3-8",
    korean: "일어나다",
    meaning: "起床 / to get up",
    part_of_speech: "V",
    origin: "固有語",
    example_sentence: "",
    related_words: "",
    chapters: ["5-3"],
    source: "課本",
    quiz_count: 0,
    correct_streak: 0,
    familiarity: "no"
  },
  {
    id: "vocab-5-3-9",
    korean: "샤워를 하다",
    meaning: "洗澡、淋浴 / to take a shower",
    part_of_speech: "V",
    origin: "外來語",
    example_sentence: "",
    related_words: "",
    chapters: ["5-3"],
    source: "課本",
    quiz_count: 0,
    correct_streak: 0,
    familiarity: "no"
  },
  {
    id: "vocab-5-3-10",
    korean: "화장을 하다",
    meaning: "化妝 / to do one's make-up",
    part_of_speech: "V",
    origin: "漢字詞",
    example_sentence: "",
    related_words: "",
    chapters: ["5-3"],
    source: "課本",
    quiz_count: 0,
    correct_streak: 0,
    familiarity: "no"
  },
  {
    id: "vocab-5-3-11",
    korean: "식사를 하다",
    meaning: "吃飯、用餐 / to have a meal",
    part_of_speech: "V",
    origin: "漢字詞",
    example_sentence: "",
    related_words: "",
    chapters: ["5-3"],
    source: "課本",
    quiz_count: 0,
    correct_streak: 0,
    familiarity: "no"
  },
  {
    id: "vocab-5-3-12",
    korean: "SNS를 하다",
    meaning: "使用社群媒體 / to use social media",
    part_of_speech: "V",
    origin: "外來語",
    example_sentence: "",
    related_words: "",
    chapters: ["5-3"],
    source: "課本",
    quiz_count: 0,
    correct_streak: 0,
    familiarity: "no"
  },
  {
    id: "vocab-5-3-13",
    korean: "경치",
    meaning: "風景 / scenery, view",
    part_of_speech: "N",
    origin: "漢字詞",
    example_sentence: "",
    related_words: "",
    chapters: ["5-3"],
    source: "課本",
    quiz_count: 0,
    correct_streak: 0,
    familiarity: "no"
  },
  {
    id: "vocab-5-3-14",
    korean: "동안",
    meaning: "期間、之間 / during",
    part_of_speech: "N",
    origin: "固有語",
    example_sentence: "",
    related_words: "",
    chapters: ["5-3"],
    source: "課本",
    quiz_count: 0,
    correct_streak: 0,
    familiarity: "no"
  },
  {
    id: "vocab-5-3-15",
    korean: "시간",
    meaning: "小時、時間 / hour, time",
    part_of_speech: "N",
    origin: "漢字詞",
    example_sentence: "",
    related_words: "",
    chapters: ["5-3"],
    source: "課本",
    quiz_count: 0,
    correct_streak: 0,
    familiarity: "no"
  },
  {
    id: "vocab-5-3-16",
    korean: "외출",
    meaning: "外出 / outing",
    part_of_speech: "N",
    origin: "漢字詞",
    example_sentence: "",
    related_words: "",
    chapters: ["5-3"],
    source: "課本",
    quiz_count: 0,
    correct_streak: 0,
    familiarity: "no"
  },
  {
    id: "vocab-5-3-17",
    korean: "젓가락",
    meaning: "筷子 / chopsticks",
    part_of_speech: "N",
    origin: "固有語",
    example_sentence: "",
    related_words: "포크",
    chapters: ["5-3"],
    source: "課本",
    quiz_count: 0,
    correct_streak: 0,
    familiarity: "no"
  },
  {
    id: "vocab-5-3-18",
    korean: "제주도",
    meaning: "濟州島 / Jeju Island",
    part_of_speech: "N",
    origin: "漢字詞",
    example_sentence: "",
    related_words: "",
    chapters: ["5-3"],
    source: "課本",
    quiz_count: 0,
    correct_streak: 0,
    familiarity: "no"
  },
  {
    id: "vocab-5-3-19",
    korean: "카메라",
    meaning: "相機 / camera",
    part_of_speech: "N",
    origin: "外來語",
    example_sentence: "",
    related_words: "",
    chapters: ["5-3"],
    source: "課本",
    quiz_count: 0,
    correct_streak: 0,
    familiarity: "no"
  },
  {
    id: "vocab-5-3-20",
    korean: "컴퓨터",
    meaning: "電腦 / computer",
    part_of_speech: "N",
    origin: "外來語",
    example_sentence: "",
    related_words: "",
    chapters: ["5-3"],
    source: "課本",
    quiz_count: 0,
    correct_streak: 0,
    familiarity: "no"
  },
  {
    id: "vocab-5-3-21",
    korean: "포크",
    meaning: "叉子 / fork",
    part_of_speech: "N",
    origin: "外來語",
    example_sentence: "",
    related_words: "젓가락",
    chapters: ["5-3"],
    source: "課本",
    quiz_count: 0,
    correct_streak: 0,
    familiarity: "no"
  },
  {
    id: "vocab-5-3-22",
    korean: "하루",
    meaning: "一天 / day, one day",
    part_of_speech: "N",
    origin: "固有語",
    example_sentence: "",
    related_words: "",
    chapters: ["5-2", "5-3"],
    source: "課本",
    quiz_count: 0,
    correct_streak: 0,
    familiarity: "no"
  },
  ...chapter52Vocabulary,
  ...chapter61Vocabulary
];

export const mockGrammar: Grammar[] = [
  {
    id: "grammar-1",
    pattern: "N에 가요",
    meaning_zh: "（平輩）去某地",
    meaning_en: "go to a place",
    example_sentence: "저는 학교에 가요.",
    cloze_question: "저는 학교__ 가요.",
    cloze_answer: "에",
    translation_question: "我要去學校。",
    translation_reference_answer: "저는 학교에 가요.",
    extra_vocab_explanation: "학교 = 學校",
    chapters: ["1-1"],
    source: "課本",
    quiz_count: 3,
    correct_streak: 3,
    familiarity: "yes"
  },
  {
    id: "grammar-2",
    pattern: "N에서 V",
    meaning_zh: "（平輩）在某地做某事",
    meaning_en: "do something at a place",
    example_sentence: "저는 학교에서 공부해요.",
    cloze_question: "저는 학교__ 공부해요.",
    cloze_answer: "에서",
    translation_question: "我在學校讀書。",
    translation_reference_answer: "저는 학교에서 공부해요.",
    extra_vocab_explanation: "공부하다 = 讀書",
    chapters: ["2-1"],
    source: "課本",
    quiz_count: 1,
    correct_streak: 1,
    familiarity: "no"
  },
  ...chapter52Grammar,
  ...chapter61Grammar
];

export const mockSettings: UserSettings = {
  id: "settings-1",
  user_id: "mock-user",
  learning_start_date: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10)
};

export const mockSessions: QuizSession[] = [
  {
    id: "session-1",
    date: new Date().toISOString().slice(0, 10),
    score_correct: 34,
    score_total: 40,
    selected_chapters: ["1-1", "2-1"]
  }
];

export const mockAnswers: QuizAnswer[] = [
  {
    id: "answer-1",
    quiz_session_id: "session-1",
    item_type: "vocabulary",
    item_id: "vocab-1",
    question_type: "vocab_zh_to_ko",
    question_text: "日期 / date",
    user_answer: "날짜",
    correct_answer: "날짜",
    is_correct: true
  },
  {
    id: "answer-2",
    quiz_session_id: "session-1",
    item_type: "grammar",
    item_id: "grammar-1",
    question_type: "grammar_cloze",
    question_text: "저는 학교__ 가요.",
    user_answer: "에",
    correct_answer: "에",
    is_correct: true
  }
];

export const allChapters = Array.from(
  new Set([...mockVocabulary.flatMap((item) => item.chapters), ...mockGrammar.flatMap((item) => item.chapters)])
).sort();
